### ISSUE TITLE
error while installing project

### ISSUE THREAD

**Issue by vetsinen** [Vivify-Ideas/nestjs-boilerplate#25]
./init

[2021-06-20T14:25:37+0300]: Looks like both docker and docker-compose are installed, everything looks good.

[2021-06-20T14:25:37+0300]: Copying .env.example -> .env

[2021-06-20T14:25:37+0300]: Starting docker-compose stack if not already started..

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

**Comment by MrGagi** [comment]
I don't think this is related to boilerplate, seems like this issue https://github.com/docker/compose/issues/7896
